### PR TITLE
rename *.css.scss to *.scss

### PR DESCRIPTION
**Pull request by rasefon**
rename *.css.scss to *.scss

### CODE REVIEW

**Comment by mtarnovan** [comment]
closes #7

**Comment by mtarnovan** [comment]
@rasefon Thanks for the PR.

**Comment by playerace** [comment]
Hi @mtarnovan, can the gem version be updated? The one on rubygems doesn't have this PR. :+1:

**Comment by mtarnovan** [comment]
Sorry for the delay @playerace - I just released 1.0.2.2 which includes this PR.

**Comment by playerace** [comment]
Great. Thanks a lot!
:+1:

**Pull request merged**
